version: '3'
networks: {}
volumes:
  dockerdev-mariadb-volume:
    external: true
  dockerdev-workspace-volume:
    external: true

services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: magento2
      db_ROOT_PASSWORD: magento2
    network_mode: bridge
    volumes:
      - dockerdev-mariadb-volume:/var/lib/mysql:rw
    ports:
      - "3308:3306"

  mailcatch:
    image: mailhog/mailhog
    network_mode: bridge

  php56:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php5-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  php70:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php7-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  php71:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php71-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - mailcatch
      - db
      - redis
    network_mode: bridge
  php72:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php72-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - mailcatch
      - redis
      - db
    network_mode: bridge
  php73:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php73-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
      - MFTF_DEBUG=1
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  php74:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php74-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
      - MFTF_DEBUG=1
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    network_mode: bridge
  php80:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php80-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - mailcatch
      - redis
      - db
    network_mode: bridge

  php81:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php81-fpm
    environment:
      - "BLACKFIRE_AGENT_SOCKET=unix:///dev/null"
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - mailcatch
      - redis
      - db
    network_mode: bridge

  redis:
    image: redis:alpine
    network_mode: bridge

  web:
    build:
      context: build/dist/web
    volumes:
      - dockerdev-workspace-volume:/data:ro
    environment:
      - DOMAINSUFFIX
    links:
      - mailcatch
      - php71:fpm
      - php70:fpm70
      - php56:fpm56
      - php71:fpm71
      - php72:fpm72
      - php73:fpm73
      - php74:fpm74
      - php80:fpm80
      - php81:fpm81
    network_mode: bridge
  ssl:
    build:
      context: build/dist/ssl
    ports:
      - "80:80"
      - "443:443"
    network_mode: bridge
